'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.3603
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sonic_2_Text_Code_Generator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ; ==========================================================================
        '''; -------------------------------------------------------------------------
        '''; Sonic 2 Text Code Generator (End Of Level Title Card Mappings)
        '''; -------------------------------------------------------------------------
        '''; Created by: Selbi (2010)
        '''; 
        '''; Thanks to:
        '''; - IDA, for kind of helping at converting the binary into an ASM file
        '''; - Xenowhirl, for his SonMapED tool
        '''; - shobiz, for answering some questions in the Basic Q&amp;A  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property EOLMappings() As String
            Get
                Return ResourceManager.GetString("EOLMappings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ; ==========================================================================
        '''; -------------------------------------------------------------------------
        '''; Sonic 2 Text Code Generator (Title Card Mappings)
        '''; -------------------------------------------------------------------------
        '''; Created by: Selbi (2010)
        '''; 
        '''; Thanks to:
        '''; - IDA, for kind of helping at converting the binary into an ASM file
        '''; - Xenowhirl, for his SonMapED tool
        '''; - shobiz, for answering some questions in the Basic Q&amp;A thread
        '''; - W [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Mappings() As String
            Get
                Return ResourceManager.GetString("Mappings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ; ==========================================================================
        '''; -------------------------------------------------------------------------
        '''; Sonic 2 Text Code Generator (Title Card Mappings)
        '''; -------------------------------------------------------------------------
        '''; Created by: Selbi (2010)
        '''; 
        '''; Thanks to:
        '''; - IDA, for kind of helping at converting the binary into an ASM file
        '''; - Xenowhirl, for his SonMapED tool
        '''; - shobiz, for answering some questions in the Basic Q&amp;A thread
        '''; - W [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Setup() As String
            Get
                Return ResourceManager.GetString("Setup", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
